volumes:
  postgres_data: {}

services:
  postgres:
    image: postgres:latest
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env
    ports:
      - ${POSTGRES_PORT}:5432

  redis:
    image: redis:6
    ports:
      - 6379:6379
